global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'file-alerts'

receivers:
- name: 'file-alerts'
  webhook_configs:
  - url: 'http://localhost:9093/api/v2/alerts'  
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname']
