FROM python:3.12.3-slim

# Set working directory inside the container
WORKDIR /app

# Copy your training code into the container
COPY train/ /app/train/

# Install Python dependencies
RUN pip install --no-cache-dir -r train/requirements.txt

# Clean up to reduce image size (apt cache isn't used here, but just in case)
RUN rm -rf /root/.cache /var/lib/apt/lists/*

# Set environment variable (optional)
ENV MLFLOW_TRACKING_URI=http://mlflow-server:5000

# Default command to run the training pipeline
CMD ["python", "train/train.py", "--no-pylint", "run", "--use_hyperopt", "true"]
