groups:
- name: ml_model_alerts
  rules:
  - alert: HighErrorRate
    expr: rate(http_requests_total{status=~"5..|4.."}[5m]) / rate(http_requests_total[5m]) > 0.5
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: High error rate detected
      description: Error rate is over 50% in the last 5 minutes

  - alert: LowConfidenceScore
    expr: model_confidence_score < 0.6
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: Low model confidence
      description: Model confidence score is below 0.6 for 5 minutes

  - alert: HighCPUUsage
    expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: High CPU usage
      description: CPU usage is above 80%

  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: High memory usage
      description: Memory usage is above 80%

  - alert: HighLatency
    expr: rate(model_prediction_seconds_sum[5m]) / rate(model_prediction_seconds_count[5m]) > 0.5
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: High prediction latency
      description: Average prediction time is above 500ms over 2 minutes
      
- name: AllInstances
  rules:
  # - alert: InstanceDown
  #   expr: up == 0
  #   for: 2m
  #   annotations:
  #     title: 'Instance {{ $labels.instance }} down'
  #     description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 2 minute.'
  #   labels:
  #     severity: 'critical'

  - alert: GPUMetricsDown
    expr: up{job="gpu_metrics"} == 0
    for: 2m
    annotations:
      title: 'GPU Metrics Instance {{ $labels.instance }} down'
      description: 'GPU metrics endpoint {{ $labels.instance }} of job {{ $labels.job }} has been down for more than 2 minute.'
    labels:
      severity: 'critical'
      service: 'gpu'

  - alert: ModelServingDown
    expr: up{job="model-serving"} == 0
    for: 3m
    annotations:
      title: 'Model Serving Instance {{ $labels.instance }} down'
      description: 'Model serving endpoint {{ $labels.instance }} of job {{ $labels.job }} has been down for more than 3 minute.'
    labels:
      severity: 'critical'
      service: 'model'

  - alert: FastAPIDown
    expr: up{job="fastapi"} == 0
    for: 3m
    annotations:
      title: 'FastAPI Instance {{ $labels.instance }} down'
      description: 'FastAPI endpoint {{ $labels.instance }} of job {{ $labels.job }} has been down for more than 3 minute.'
    labels:
      severity: 'critical'
      service: 'api'