global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'model-serving'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['model-serving:5050']
    scrape_interval: 5s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'gpu_metrics'
    static_configs:
      - targets: ['localhost:9400']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'fastapi'
    static_configs:
      - targets: ['model-serving:5050']
      # - targets: ['host.docker.internal:5050']  
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 4s
